name: VDTDistance
main: tech.underside.mikelplayz.VDTPlugin
version: 1.0
api-version: 1.21.10
author: MikelPlayz
commands:
  vdt:
    description: Adjust server view and simulation distances
    usage: /vdt <viewdistance|simulationdistance> <number>
    permission: vdt.use
permissions:
  vdt.use:
    description: Allows use of /vdt commands
    default: op
